name: Sync Github To Image

on:
  push:
    branches: [main]
  #schedule:
    # 定时任务，每天 UTC 时间 0 点运行
    #- cron: "0 0 * * *"
  #workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 为了 git pull --unshallow，我们需要获取所有的提交历史
  
      - name: Sync To GitCode
        uses: AlianBlank/github.sync.image@1.0.0
        with:
          SSH_ID_RSA: ${{ secrets.GITCODE_ID_RSA }}
          KNOWN_HOSTS: gitcode.net
          REMOTE_NAME: gitcode
          REPOSITORY_URL: ${{ github.Repository }}
          BRANCH_NAME: ${{ github.ref.name }}
          GIT_EMAIL: wangfj11@foxmail.com
          GIT_NAME: AlianBlank
