name: Sync Github To Image

on:
  push:
    branches: [main]
  #schedule:
    # 定时任务，每天 UTC 时间 0 点运行
    #- cron: "0 0 * * *"
  #workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 为了 git pull --unshallow，我们需要获取所有的提交历史

      # 设置 SSH
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: gitcode.net
          private-key: ${{ secrets.GITCODE_ID_RSA }}
      # 同步GIT
      - name: Sync To GitCode
        uses: AlianBlank/github.sync.image@1.0.7
        with:
          REMOTE_NAME: gitcode
          GIT_EMAIL: wangfj11@foxmail.com
          GIT_NAME: AlianBlank

